name: extract File

on:
  push:
    branches:
      - main  # Workflow berjalan saat ada perubahan di branch 'main'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List ZIP files in repository
      run: ls -l "*.zip"

    - name: Create extraction folder
      run: mkdir extracted

    - name: Extract ZIP files
      run: unzip "*.zip" -d extracted/

    - name: Commit and Push Extracted Files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add extracted/*
        git commit -m "Extracted ZIP files"
        git push
