name: Unzip Video File

on:
  push:
    paths:
      - "*.zip"  # Memicu workflow saat file ZIP di-push
    branches:
      - main  # Memicu workflow saat ada perubahan di branch main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List all files in repository
      run: ls -l

    - name: Extract video.zip file
      run: unzip video.zip -d extracted/  # Ganti path jika perlu

    - name: Commit and Push Extracted Files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add extracted/*
        git commit -m "Extracted video.zip"
        git push
