name: Unzip Files Workflow

on:
  push:
    paths:
      - "*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List all files in repository
      run: ls -l

    - name: Create extraction directory
      run: mkdir -p extracted/

    - name: Extract ZIP files
      run: sh -c 'unzip "*.zip" -d extracted/'

    - name: Commit and Push Extracted Files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add extracted/*
        git commit -m "Extracted ZIP files"
        git push
